// <auto-generated />
using System;
using Ksiegarnia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ksiegarnia.Migrations
{
    [DbContext(typeof(BookstoreContex))]
    [Migration("20250513154324_UpdateCoverUrl")]
    partial class UpdateCoverUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ksiegarnia.Entities.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numer_mieszkania");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("miejscowosc");

                    b.Property<string>("HomeNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numer_domu");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ulica");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("kod_pocztowy");

                    b.HasKey("ID");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imie");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narodowosc");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwisko");

                    b.HasKey("ID");

                    b.ToTable("Autorzy");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Autora");

                    b.Property<string>("CoverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa_obrazu");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gatunek");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jezyk");

                    b.Property<int>("Pages")
                        .HasColumnType("integer")
                        .HasColumnName("ilosc_stron");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cena");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tytul");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Ksiazki");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorID = 1,
                            CoverName = "pan_tadeusz.jpg",
                            Description = "Najważniejsze dzieło polskiego romantyzmu.",
                            Genre = "Epopeja",
                            Language = "Polski",
                            Pages = 320,
                            Price = 39.99m,
                            Title = "Pan Tadeusz"
                        },
                        new
                        {
                            ID = 2,
                            AuthorID = 2,
                            CoverName = "to.jpg",
                            Description = "Przerażająca historia o kosmicznym złu w małym miasteczku.",
                            Genre = "Horror",
                            Language = "Angielski",
                            Pages = 512,
                            Price = 49.99m,
                            Title = "To"
                        },
                        new
                        {
                            ID = 6,
                            AuthorID = 41,
                            CoverName = "lalka.jpg",
                            Description = "Klasyczna powieść Bolesława Prusa.",
                            Genre = "Powieść",
                            Language = "Polski",
                            Pages = 640,
                            Price = 49.99m,
                            Title = "Lalka"
                        },
                        new
                        {
                            ID = 7,
                            AuthorID = 42,
                            CoverName = "1984.jpg",
                            Description = "Powieść George'a Orwella o totalitarnym państwie.",
                            Genre = "Dystopia",
                            Language = "Angielski",
                            Pages = 328,
                            Price = 39.99m,
                            Title = "1984"
                        },
                        new
                        {
                            ID = 8,
                            AuthorID = 43,
                            CoverName = "mistrz_malgorzata.jpg",
                            Description = "Rosyjska powieść Michaiła Bułhakowa.",
                            Genre = "Powieść",
                            Language = "Rosyjski",
                            Pages = 384,
                            Price = 55.00m,
                            Title = "Mistrz i Małgorzata"
                        });
                });

            modelBuilder.Entity("Ksiegarnia.Entities.BookAuthor", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Ksiazki");

                    b.Property<int>("AuthorID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Autora");

                    b.Property<int>("ID")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.HasKey("BookID", "AuthorID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Autorzy_Ksiazki");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AddressID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Adresu");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imie");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("haslo");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefon");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwisko");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Orders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Klienta");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_zamowienia");

                    b.Property<decimal>("PirceOrder")
                        .HasColumnType("numeric")
                        .HasColumnName("kwota");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.OrdersBooks", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Ksiazki");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Zamowienia");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("ilosc");

                    b.Property<decimal>("BookPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("cena_ksiazki");

                    b.HasKey("BookID", "OrderID");

                    b.HasIndex("OrderID");

                    b.ToTable("Zamowienia_Ksiazki");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Book", b =>
                {
                    b.HasOne("Ksiegarnia.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.BookAuthor", b =>
                {
                    b.HasOne("Ksiegarnia.Entities.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ksiegarnia.Entities.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Customer", b =>
                {
                    b.HasOne("Ksiegarnia.Entities.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("AddressID");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Orders", b =>
                {
                    b.HasOne("Ksiegarnia.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.OrdersBooks", b =>
                {
                    b.HasOne("Ksiegarnia.Entities.Book", "Book")
                        .WithMany("OrderBooks")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ksiegarnia.Entities.Orders", "Orders")
                        .WithMany("OrderBooks")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Address", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("OrderBooks");
                });

            modelBuilder.Entity("Ksiegarnia.Entities.Orders", b =>
                {
                    b.Navigation("OrderBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
