// <auto-generated />
using System;
using Ksiegarnia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ksiegarnia.Migrations
{
    [DbContext(typeof(BookstoreContex))]
    [Migration("20250427111749_SeedBooks")]
    partial class SeedBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ksiegarnia.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("Ksiegarnia.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imie");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narodowosc");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwisko");

                    b.HasKey("ID");

                    b.ToTable("Autorzy");
                });

            modelBuilder.Entity("Ksiegarnia.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Autora");

                    b.Property<string>("CoverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa_obrazu");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gatunek");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jezyk");

                    b.Property<int>("Pages")
                        .HasColumnType("integer")
                        .HasColumnName("ilosc_stron");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cena");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tytul");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Ksiazki");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorID = 1,
                            CoverName = "pan_tadeusz.jpg",
                            Description = "Najważniejsze dzieło polskiego romantyzmu.",
                            Genre = "Epopeja",
                            Language = "Polski",
                            Pages = 320,
                            Price = 39.99m,
                            Title = "Pan Tadeusz"
                        },
                        new
                        {
                            ID = 2,
                            AuthorID = 2,
                            CoverName = "to.jpg",
                            Description = "Przerażająca historia o kosmicznym złu w małym miasteczku.",
                            Genre = "Horror",
                            Language = "Angielski",
                            Pages = 512,
                            Price = 49.99m,
                            Title = "To"
                        },
                        new
                        {
                            ID = 3,
                            AuthorID = 3,
                            CoverName = "harry_potter.jpg",
                            Description = "Pierwsza część serii o młodym czarodzieju.",
                            Genre = "Fantasy",
                            Language = "Polski",
                            Pages = 328,
                            Price = 45.50m,
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            ID = 4,
                            AuthorID = 4,
                            CoverName = "wiedzmin.jpg",
                            Description = "Pierwszy zbiór opowiadań o Wiedźminie Geralcie.",
                            Genre = "Fantasy",
                            Language = "Polski",
                            Pages = 288,
                            Price = 42.00m,
                            Title = "Ostatnie życzenie"
                        },
                        new
                        {
                            ID = 5,
                            AuthorID = 5,
                            CoverName = "gra_o_tron.jpg",
                            Description = "Pierwszy tom sagi 'Pieśni Lodu i Ognia'.",
                            Genre = "Fantasy",
                            Language = "Polski",
                            Pages = 512,
                            Price = 55.00m,
                            Title = "Gra o tron"
                        });
                });

            modelBuilder.Entity("Ksiegarnia.BookAuthor", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorID")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<decimal>("BookPirce")
                        .HasColumnType("numeric");

                    b.HasKey("BookID", "AuthorID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Autorzy_Ksiazki");
                });

            modelBuilder.Entity("Ksiegarnia.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AddressID")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imie");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("haslo");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numer_telefonu");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwisko");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Ksiegarnia.Orders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_zamowienia");

                    b.Property<decimal>("PirceOrder")
                        .HasColumnType("numeric")
                        .HasColumnName("kwota");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("Ksiegarnia.Book", b =>
                {
                    b.HasOne("Ksiegarnia.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Ksiegarnia.BookAuthor", b =>
                {
                    b.HasOne("Ksiegarnia.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ksiegarnia.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Ksiegarnia.Customer", b =>
                {
                    b.HasOne("Ksiegarnia.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Ksiegarnia.Orders", b =>
                {
                    b.HasOne("Ksiegarnia.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ksiegarnia.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Ksiegarnia.Book", b =>
                {
                    b.Navigation("BookAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
